[build]
  publish = "build"
  command = "rm -rf build && rm -rf node_modules && npm install && npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  REACT_APP_API_URL = "https://karusaku-emr-aeza.onrender.com"
  NETLIFY_CACHE_DISABLED = "true"
  CI = "true"
  FORCE_REBUILD = "true"

[[redirects]]
  from = "/api/*"
  to = "https://karusaku-emr-aeza.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
