services:
  - type: web
    name: medical-records-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: medical-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: medical-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: medical-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: medical-db
          property: database

databases:
  - name: medical-db
    databaseName: medical_records
    user: medical_user
